### PR TITLE
V1.1

### PR DESCRIPTION
**Pull request by marcus-j-davies**
@crxporter @Shaquu 

I will be testing this on my VM's now - as the test script will fail due to locations.
if all ok - will merge

 - [x] Ubunto
 - [x] Alpine
 - [x] OSX

### CODE REVIEW

**Comment by Shaquu** [comment]
Testing on my pi4

**Comment by Shaquu** [comment]
`bash <(curl -sL https://raw.githubusercontent.com/NRCHKB/nrchkb-ffmpeg-build/v1.1/build-bootstrap.sh)`
```
   Start time: Mon 11 Apr 18:19:07 CEST 2022
   End time:   Mon 11 Apr 18:35:00 CEST 2022
   Duration:   953 seconds
   Max jobs:   3
   Option:     3
```

**Review by Shaquu — APPROVED** [review]

**Comment by marcus-j-davies** [comment]
@Shaquu 
EV of `BRANCH_NAME` works.

```
export BRANCH_NAME=v1.1
bash <(curl -sL https://raw.githubusercontent.com/NRCHKB/nrchkb-ffmpeg-build/v1.1/build-bootstrap.sh)
```


image

**Comment by marcus-j-davies** [comment]
@Shaquu @crxporter 
this is ready to merge into to `main`

all working.



1 minor update (requested by @Shaquu)
the bootstrap can now make use of a `BRANCH_NAME` EV to override the source build script branch location

**Pull request merged**
